### PR TITLE
Clean style

### PR DESCRIPTION
**Pull request by cage2**
Hi!

A friend of mine introduced me `checkdoc` so i tried to run on the source, some of the problems highlighted  did makes sense to me (especially two functions without docstring!), so i fixed the code and this is the results.

No new code has been actually added, except docstring just two error message was modified a bit.

Bye!
C.

### CODE REVIEW

**Comment by bastibe** [comment]
Brilliant! Docs work can feel tedious, but it truly is the most important user interface of our code, so kudos for cleaning it up some.

**Comment by cage2** [comment]
Hi @bastibe !

Merging in a second. :-)

I hope you're enjoying the summer! :sun_with_face: 

Bye!
C.

**Comment by bastibe** [comment]
Hi @cage2,

it's been an interesting summer so far. The kids are quite a handful during summer break, but in a good way, and we even got to go on vacation a little. I hope you're doing well, too!

**Comment by cage2** [comment]
On Fri, Aug 20, 2021 at 04:33:25AM -0700, Bastian Bechtold wrote:
> Hi @cage2,

Hi Bastian!

> it's been an interesting summer so far. The kids are quite a handful during summer break, but in a good way,

i think they needs a lot of attentions as they are full of energy! :)

> and we even got to go on vacation a little.

uh! Very well!

> I hope you're doing well, too!

We had  some hard times  because the hot  weather, i think  the region
where i live hit the  European record regarding temperature (more than
48 °C)! Not a record i would be proud honestly! ;-)

But now  it is  a bit  better and there  is even  a nice  and peaceful
sunset this evening. :-)

Bye!
C.

**Comment by bastibe** [comment]
> more than 48 °C

Wow, that's terrifying! I'm glad you're ok.

I'm actually glad that the summer back home has been mostly cool and rainy.

**Comment by cage2** [comment]
On Sun, Aug 22, 2021 at 05:55:27AM -0700, Bastian Bechtold wrote:
> > more than 48 °C
>
> Wow, that's terrifying! I'm glad you're ok.

It were  hard days  the latest,  but now  things are  getting slightly
better, fortunately (still hot though but bearable).

Bye!
C.

**Pull request merged**
