### PR TITLE
Updated section 'known bugs' of README.

### PR DESCRIPTION
**Pull request by cage2**
Hi Bastian!

I just added the problem shown in #70 to the list of `known bugs` in the README.

Also i removed a phrase mentioning problems with multiline annotations, hopefully this was addressed by a previous patch! :)

Bye!
C.

### CODE REVIEW

**Comment by bastibe** [comment]
If you ask me, a README change does not usually come with a version bump. But it's really not important and I'll leave that up to you.

Also, I would add a note that this is the way Emacs is meant to behave, and (likely) not something we can fix.

Otherwise, great work as usual!

**Comment by cage2** [comment]
On Wed, Jun 24, 2020 at 04:56:46AM -0700, Bastian Bechtold wrote:

Hi Bastian!

> If you ask me, a README change does not usually come with a version bump. But it's really not important and I'll leave that up to you.
>
> Also, I would add a note that this is the way Emacs is meant to behave, and (likely) not something we can fix.

As always, good suggestions coming from you; I just pushed the changes! :)

Bye!
C.

**Comment by bastibe** [comment]
Hi Cage,

everything looks good. Merge when you're ready.

**Comment by cage2** [comment]
> Hi Cage,

Hello Bastian!!
 
> everything looks good. Merge when you're ready.

Very well, merging! :)

Bye!
C.

**Pull request merged**
