### PR TITLE
Added procedures to generate and use a single database for each annotated file.

### LINKED ISSUE #124: [new feature] Using a file 'FILENAME.notes' to hold the annotations of file 'FILENAME'
This is a big change, as means get rid of the database.

Comments welcome!
Bye!
C.

### PR DESCRIPTION
**Pull request by cage2**
Hi!

This is my attempt to close #124. The patch is simple. So simple that i think would be a good idea to test it for a week before merging, so some possible regressions can be highlighted. ;-D

Bye!
C.

### CODE REVIEW

**Comment by bastibe** [comment]
Simple and beautiful! I like it!

**Comment by cage2** [comment]
Hi @bastibe 

> Simple and beautiful! I like it!

Great! I am going to update the necessary documentation files and will merge that!

My only doubt is: this new version will be the 1.6.0, right? 😅

Bye!
C.

**Comment by bastibe** [comment]
> this new version will be the 1.6.0, right? 😅

I would say, so, yes. A new feature means a new minor version, if we're sticking with semantic versioning.

**Comment by cage2** [comment]
On Thu, Jun 02, 2022 at 04:43:18AM -0700, Bastian Bechtold wrote:
> > this new version will be the 1.6.0, right? 😅
>
> I would say, so, yes. A new feature means a new minor version, if we're sticking with semantic versioning.

I  like semantic  version, in  fact i  try to  stick to  this kind  of
numbering in  nearly all my projects,  but I am also  always unsure to
decide the next version number. And that is why I ask so often.  :) :)

Bye!
C.

**Pull request merged**
