### PR TITLE
Restored annotation of info files.

### PR DESCRIPTION
**Pull request by cage2**
Hi @bastibe !

I am going to ask to the user that submitted the PR if this patch improve the performances with remote files too as this PR supposed to fix also #141.

Bye!
C.

### CODE REVIEW

**Comment by bastibe** [comment]
Looks good, although I don't quite understand all the intricacies. Narrowing and remote files and such sound like a headache for annotations, though.

**Comment by cage2** [comment]
On Wed, Nov 23, 2022 at 11:54:04PM -0800, you wrote:

Hi!

> Looks   good,   although   I   don't  quite   understand   all   the
> intricacies.  Narrowing  and remote  files  and  such sound  like  a
> headache for annotations, though.

I can guarantee they are a source  of headache for who write the code,
too. ;-D  I was  surprised (a  good surprise!)  that remote  files and
annotate works at all! :) I think the ability to annotate remote files
is cool!

I  hope that  this  patch will  fix  all the  issues  related to  this
features but I would not bet on it! :-D

Bye!
C.

**Comment by cage2** [comment]
Hi @bastibe !

I would merge this path, if you agree.

Bye!
C.

**Comment by cage2** [comment]
Hi!

Merging in a second!

Also happy vacation @bastibe ! :D :D 

C.

**Comment by bastibe** [comment]
And happy holidays to you, too!

**Comment by cage2** [comment]
> And happy holidays to you, too!

Thanks!! 🙏 😃
C.

**Pull request merged**
