### PR TITLE
Hide annotation text

### PR DESCRIPTION
**Pull request by cage2**
Hi!

This patch supposed to implements what is described in #149 .

Bye!
C.

### CODE REVIEW

**Comment by bastibe** [comment]
That's a unique use case for annotate. Very interesting.

Your implementation looks good.

**Comment by cage2** [comment]
Hi Bastian!

> That's a unique use case for annotate. Very interesting.

I agree, it would be an unusual scenario for this feature to be useful, but sometimes, for example, a big annotation is pushing the rest of the text too far and hiding it could be a temporary solution.
 
> Your implementation looks good.

Thanks! I would wait to merge this until @emacs-newer test this patch, they offered to check if i have implemented correctly the  feature they proposed. 

Bye!
C.

**Comment by cage2** [comment]
Hi!

I would merge this because i have some ideas for #147 and i would like to work on that issue, that seems a lot interesting to me. :smile: 

Bye!
C.

**Comment by cage2** [comment]
Hi!

OK, merging!  :rocket: :smile: 

Bye!
C.

**Pull request merged**
