### PR TITLE
Fixed version number contained in code top comment.

### PR DESCRIPTION
**Pull request by cage2**
Hi bastibe!

Nothing really critical in this PR, as you can see :)

Bye!
C.

### CODE REVIEW

**Review by bastibe — APPROVED** [review]
Merge when you're ready.

**Comment by cage2** [comment]
Hi @bastibe !

OK, merging!

Take care and stay safe in these hard times! 
C.

**Comment by bastibe** [comment]
> Take care and stay safe in these hard times!

Thank you for your continued work on annotate.el, and for caring about the humans behind it. Comments such as yours do mean a lot. Thank you.

I just tagged the new release, so it should be picked up by melpa-stable within a day or two.

**Comment by cage2** [comment]
On Sun, Aug 30, 2020 at 11:08:46PM -0700, Bastian Bechtold wrote:

Hi Bastian!

> > Take care and stay safe in these hard times!
>
> Thank you for your continued work on annotate.el,

I has become a pleasure to take  care, with my limited skills, of this
nice program! :)

> and for caring about the humans behind it.
> Comments such as yours do
> mean a lot. Thank you.

I try to never forget that code is made by humans for humans. And life
is hard (or not simple) for everybody. :)

> I  just  tagged the  new  release,  so it  should  be  picked up  by
> melpa-stable within a day or two.

That is a good idea!

Bye Bastian! :)
C.

**Pull request merged**
