### PR TITLE
Merge annotations database

### PR DESCRIPTION
**Pull request by cage2**
Hi! 

This patch will (hopefully!) fulfill #118 :)

At the moment is incomplete but i think I am starting to grasp the problem.

Status: ~~draft~~ ~~in progress~~ testing

### CODE REVIEW

**Comment by cage2** [comment]
Hi!

The procedures should be there and the command to merge two database is `annotate-import-annotations`. My testing was very limited so far and bugs are expected. Also docstrings was missing, but at least there is a starting point. :)

Bye!
C.

**Comment by bastibe** [comment]
A surprisingly large chunk of code for this seemingly-simple feature. 

Looks good to me from reading through the code, though I haven't test-run it.

**Comment by cage2** [comment]
Hi @bastibe !

OK, i think i just need to update the README and related documentation files (NEWS and changelog), also i need to increase the version number (to 1.5.0 i think!), but i wonder if the current version (1.4.3) could be tagged so that it could be included in melpa stable. This way if any bugs is going to arise with this new feature it will not affect users of the stable repository.

Bye!
C.

**Comment by bastibe** [comment]
Good idea! Feel free to add the tag.

If you want to, you can also add annotate.el to nongnu-elpa. I'm not entirely sure what is involved in that, but one kind contributor did it [here](https://github.com/bastibe/org-journal/pull/374) in my other repo. If I understand this correctly, nongnu-elpa will be available by default in the next version of Emacs.

**Comment by cage2** [comment]
Hi @bastibe !

> Good idea! Feel free to add the tag.

OK! I hope i am not going to make a mess; I will be careful, I promise! ;-D ;-D
 
> If you want to, you can also add annotate.el to nongnu-elpa. I'm not entirely sure what is involved in that, but one kind contributor did it [here](https://github.com/bastibe/org-journal/pull/374) in my other repo. If I understand this correctly, nongnu-elpa will be available by default in the next version of Emacs.

Nice! I am studying  the readme file linked from the message you provided, i think the repository is ready for inclusion in nongnu-elpa, but i need to check more carefully the documentation because i did not understand where i should make my proposal for inclusion. No problem, by the way :)

I am tagging the release and tomorrow i will merge this patch.
I think the suggestions from @fab6 was good, importing a database is an useful feature. :+1: 

Bye!
C.

**Pull request merged**
