### PR TITLE
Popup annotation

### PR DESCRIPTION
**Pull request by cage2**
Hi!!

This is a draft of what suggested by @oatmealm in #80.

I used the `help-echo` property as discussed in the same thread.

Honestly i do not like the aesthetic of the popup on my system but this is totally subjective, of course. And, moreover, i agree this feature can  help some users. So OK, i will deal with it! :-D

To activate the popup system a new customized variable has been added: `annotate-use-echo-area`.

I wonder what i am missing because this was too simple. ;-)

Bye!
C.

edit: also i removed the internal link in the README as pointed out in #79

### CODE REVIEW

**Comment by oatmealm** [comment]
Will have a look shortly... sounds helpful. 

I was just thinking, what if the annotations were shown in a side bar I.e a separate window that can be toggled on and off, while notes are synced with the main conetent buffer. 

org-noter has this nice semi-automatic (I think you need to 'C-M .' first) sync facility that advances or backtracks the notes buffer in respect to your position in the pdf-view buffer.

**Comment by cage2** [comment]
On Sun, Sep 20, 2020 at 08:24:03AM -0700, oatmealm wrote:

Hi!

> Will have a look shortly... sounds helpful.

Good! :)

> I was just thinking, what if the annotations were shown in a side bar I.e a separate window that can be toggled in and out while notes are synced with the cone tent buffer.
>
> org-noter has this nice semi-automatic (I think you need to 'C-M .' first) sync facility that advances or backtracks the notes buffer in respect to your position in the pdf-view buffer.

You  could  (sort  of)  use  the summary  window  for  something  like
that. Just search the database for the current file that the buffer is
visiting.

This will show all the annotation contained in the buffer, though.

Although maybe  could not be  too difficult  to write a  function that
makes that search for the user and  cuts the summary to shown only the
annotations that annotates text beyond  the current cursor position in
the buffer.

Interesting! But I have to think a bit about that! 🤔

Bye!
C.

**Comment by oatmealm** [comment]
Looks nice :+1: 

In the echo area "הערה מס 1" (comment no 1) ...

BTW the pointer was on the annotation in the buffer, but wasn't captured... the selection in blue is there by accident.

Must say though it's still probably more useful when in the buffer closer to the text. 

gnome-shell-screenshot-5KLIR0

**Comment by cage2** [comment]
Hi!

> Looks nice +1

That's good! :)

> In the echo area "הערה מס 1" (comment no 1) ...

I think this is dependents from the Emacs configuration (perhaps at compile time)   or graphical toolkit used, please take a look at the results i get in the image below:

https://www.autistici.org/interzona/img/misc/popup.png

Yes seems there is an broken icon, no idea why! ;-)

> Must say though it's still probably more useful when in the buffer closer to the text.

I agree, i think the old behaviour could be the default.

Anyway i like the idea to use a window to summarize the annotation in a single file! :)

Bye!

**Comment by cage2** [comment]
Hi @oatmealm!

I have added a new command: `annotate-summary-of-file-from-current-pos` that shows annotation in the active buffer that appears after the cursor position. Can you, please, take a look if this feature is more or less the suggestion you made in your first comment of this thread?
Thank you!

C.

**Review by bastibe — APPROVED** [review]

**Comment by bastibe** [comment]
This looks like a useful addition to annotate.el, in particular for typographically difficult scenarios such as variable-width fonts or overlay-heavy modes. I like it. Good work!

**Comment by oatmealm** [comment]
> Can you, please, take a look if this feature is more or less the suggestion you made in your first comment of this thread?


Sorry. Didn't see this before. Will have a look!

**Comment by cage2** [comment]
On Mon, Sep 28, 2020 at 03:28:04AM -0700, Bastian Bechtold wrote:

Hi Bastian!

> This looks like a useful  addition to annotate.el, in particular for
> typographically difficult scenarios such  as variable-width fonts or
> overlay-heavy modes. I like it. Good work!

Thank you!   Part of the merits  goes to oatmealm that  suggested both
and is helping with testing! Honestly  this was not too difficult as i
am building on  top of existing package's code (and  Emacs of course).
Things seemes to go quite  smooth...until fonts enter in the equation!
😉😉

Seriously, i  think we  are giving  users more  options to  adapt this
package  in their  setup.  But  i would  still  like  to explore  your
proposal about using Unicode space (thin, hair and similar).

Now, may i ask you two question:

- i think  the content  of your  message, slightly  rephrased perhaps,
  could go  into the readme  as this  provide a possible  solution for
  persons  that uses  variable-width fonts,  what do  you think  about
  that?

- which one supposed to be the next version number (after merging this
  PR): 0.8.4 seems to low but 0.9.0  to much instead, wich one is your
  opinion?

Bye!
C.

**Comment by cage2** [comment]
On Mon, Sep 28, 2020 at 05:10:07AM -0700, oatmealm wrote:

Hi oatmealm!

> > Can you, please, take a look if this feature is more or less the suggestion you made in your first comment of this thread?
>
>
> Sorry. Didn't see this before. Will have a look!

No need to be sorry, i am not in a hurry ;), just take your time :)

Bye!
C.

**Comment by bastibe** [comment]
> - i think the content of your message, slightly rephrased perhaps, could go into the readme as this provide a possible solution for persons that uses variable-width fonts, what do you think about that? 

Good idea!

> - which one supposed to be the next version number (after merging this PR): 0.8.4 seems to low but 0.9.0 to much instead, which one is your opinion?

Since this is a feature addition, it should go into the minor version, i.e. 0.9.0. I generally try to adhere to the semantic versioning convention of *major.minor.bugfix*, where major versions are for big milestones or backwards-incompatible changes, minor versions are for additions, and bugfix versions are for bugfixes only.

**Comment by oatmealm** [comment]
@cage2 ~~What should I check out? Couldn't find this function on you pull request #81~~ ...

Ok, my bad. Problems is that on this branch I'm having serious problems with showing annotations. They sometimes appear, sometime not, and never written to the db...

I keep getting "The annotation database is empty" when I try the new command, and indeed the file pointed to by 'annotate-file' never gets written to...

**Comment by cage2** [comment]
Hi @oatmealm 

> @cage2 ~What should I check out? Couldn't find this function on you pull request #81~ ...
> 
> Ok, my bad. Problems is that on this branch I'm having serious problems with showing annotations. They sometimes appear, sometime not, and never written to the db...
> 
> I keep getting "The annotation database is empty" when I try the new command, and indeed the file pointed to by 'annotate-file' never gets written to...

I am sorry that you are having trouble, can you share a little file where the problem shows as you did before?

Bye!
C.

**Comment by cage2** [comment]
Hi @bastibe !

> > * i think the content of your message, slightly rephrased perhaps, could go into the readme as this provide a possible solution for persons that uses variable-width fonts, what do you think about that?
> 
> Good idea!

Very well!

> > * which one supposed to be the next version number (after merging this PR): 0.8.4 seems to low but 0.9.0 to much instead, which one is your opinion?
> 
> Since this is a feature addition, it should go into the minor version, i.e. 0.9.0. I generally try to adhere to the semantic versioning convention of _major.minor.bugfix_, where major versions are for big milestones or backwards-incompatible changes, minor versions are for additions, and bugfix versions are for bugfixes only.

I think you already explained me the convention you adopted for this program but still semantic versioning just do not enter in my mind. And i even think it is a good convention! :-D

Anyway i can see now that 0.9.0  is the right version number, and i promise this is the last time you need to explain semantic version! :-D :-D

Bye!
C.

**Comment by bastibe** [comment]
> Anyway i can see now that 0.9.0 is the right version number, and i promise this is the last time you need to explain semantic version! :-D :-D

No problem at all ;-)

**Comment by cage2** [comment]
Hi @oatmealm!

Sorry to bother you but i wonder if you could provide a way i can reproduce the bug you met with this branch.

Bye!
C.

**Comment by cage2** [comment]
Hi Bastibe!

I can not reproduce  the bug pointed out by oatmealm,  so i propose to
merge it anyway. What is your opinion?

Bye!
C.

**Comment by bastibe** [comment]
> I can not reproduce the bug pointed out by oatmealm, so i propose to merge it anyway. What is your opinion?

If it looks good on your end, I'd say we merge it now, and deal with potential regressions later.

**Comment by cage2** [comment]
Hi @bastibe!

> If it looks good on your end, I'd say we merge it now, and deal with potential regressions later.

Let's merge then! :-)

Bye!
C.

**Pull request merged**
