### PR TITLE
Fixed deletion of annotations;

### PR DESCRIPTION
**Pull request by cage2**
Hi @bastibe   

This a quick fix for properly deletion of annotation using `C-d`. Also an Emacs maintainer asked me to add an email address on one of the top comments of the file as this is used to notify problem building the package on NonGNU ELPA. I would add my email but i thought asking you before was the right thing to do, i am OK if you want to add your instead too,  so choose freely! :)

Bye!
C.

### CODE REVIEW

**Comment by bastibe** [comment]
Great!

Do feel free to add your email address. If you want to, I'll happily sign this repository over to your account as well. You are a great steward for annotate.el!

**Comment by cage2** [comment]
On Wed, Mar 02, 2022 at 12:33:19AM -0800, Bastian Bechtold wrote:

Hi Bastian!

> Do feel free to add your email address. If you want to, I'll happily
> sign this repository over to your account as well.

I have added my email to the mintainer line, i have wrote my name just
before the  address because i fear  someone could think this  was your
address and flooding your mailbox  with complains about how much buggy
the code is :D  :D :D (this is a joke, nothing  like that happened and
instead we got a lot of useful feedback from users)!

Also i  have added a few  changes suggested after discussing  with and
Emacs developer a  bit more, no radical changes but  probably we got a
cleaner code.

>You are a great steward for annotate.el!

In any case, only thanks to your help! :)
C.

**Comment by bastibe** [comment]
Please merge when you're ready!

**Comment by cage2** [comment]
Hi!

Merging in a second! :-)
Bye!
C.

**Pull request merged**
