### PR TITLE
Print message annotate under point

### PR DESCRIPTION
**Pull request by cage2**
Hi!

With this patch i believe #136 could be closed!

Bye!
C.

### CODE REVIEW

**Comment by bastibe** [comment]
Neat! Great idea!

I wonder about the default delay of 0.1 s, though. That seems unexpectedly low, I'd have expected something like 0.5 s, as with e.g. completion libraries. On the other hand, maybe you'd really want the annotation to show up immediately, i.e. with a very short delay. I guess that means the delay should be configurable.

**Comment by cage2** [comment]
On Thu, Sep 22, 2022 at 01:27:59AM -0700, you wrote:

Hi Bastibe!!

> Neat! Great idea!

All the merits goes to alienbogart, they suggested that feature.

> I  wonder about  the  default delay  of 0.1  s,  though. That  seems
> unexpectedly low,  I'd have expected  something like 0.5 s,  as with
> e.g. completion  libraries. On  the other  hand, maybe  you'd really
> want the annotation  to show up immediately, i.e. with  a very short
> delay. I guess that means the delay should be configurable.

Honestly there is no reason that  makes me choose that value as delay;
it is more or  less a random value but, as you  wrote, small enough to
be unnoticeable.  I think your suggestion to make it customizable (and
defaulting to  0.5s) is the right  thing to do! Thanks  for suggesting
that change! :)

Bye!
C.

**Comment by cage2** [comment]
Hi @bastibe!

Finally i have found the time to (hopefully!) complete this patch! :) :)

Bye!
C.

**Comment by bastibe** [comment]
Looks good!

**Comment by cage2** [comment]
Hi @bastibe !

Very well, i am going to merge this in a minute!

I am sorry i am slowing down working on this package but i have been very busy lately, but i can guarantee i still want to take care of this package! :)

Thanks for reviewing my code!
C.

**Comment by bastibe** [comment]
Do not worry, @cage2. There's absolutely no obligation to work on this. Please only work on annotate if and when it's fun to you.

**Comment by cage2** [comment]
Hi @bastibe !

> Please only work on annotate if and when it's fun to you.

I find absolutely fun to work on annotate! :) 

I am sorry that lately i had not so much time to work on all my FLOSS projects. I hope things will get better in future, and also that new ideas for this package comes from us or the people that are using the package (like in this case)!

Bye!
C.

**Pull request merged**
